'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ATE_Licenses_Etc_Backup.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AS2A_MY49430174_2011_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2A_MY49430174_2011_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS2A_MY49430174_2011_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2A_MY49430174_2011_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS2A_MY49430174_2011_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2A_MY49430174_2011_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS2B_MY49430173_2011_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2B_MY49430173_2011_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS2B_MY49430173_2011_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2B_MY49430173_2011_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS2B_MY49430173_2011_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS2B_MY49430173_2011_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3A_MY49430202_2012_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3A_MY49430202_2012_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3A_MY49430202_2012_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3A_MY49430202_2012_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3A_MY49430202_2012_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3A_MY49430202_2012_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3B_MY49430198_2012_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3B_MY49430198_2012_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3B_MY49430198_2012_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3B_MY49430198_2012_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS3B_MY49430198_2012_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS3B_MY49430198_2012_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4A_MY49430215_2012_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4A_MY49430215_2012_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4A_MY49430215_2012_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4A_MY49430215_2012_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4A_MY49430215_2012_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4A_MY49430215_2012_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4B_MY49430214_2012_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4B_MY49430214_2012_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4B_MY49430214_2012_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4B_MY49430214_2012_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS4B_MY49430214_2012_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS4B_MY49430214_2012_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5A_SG44420142_2005_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5A_SG44420142_2005_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5A_SG44420142_2005_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5A_SG44420142_2005_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5A_SG44420142_2005_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5A_SG44420142_2005_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5B_SG44420130_2005_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5B_SG44420130_2005_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5B_SG44420130_2005_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5B_SG44420130_2005_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS5B_SG44420130_2005_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS5B_SG44420130_2005_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6A_SG44420114_2005_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6A_SG44420114_2005_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6A_SG44420114_2005_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6A_SG44420114_2005_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6A_SG44420114_2005_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6A_SG44420114_2005_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6B_SG01040410_2002_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6B_SG01040410_2002_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6B_SG01040410_2002_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6B_SG01040410_2002_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS6B_SG01040410_2002_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS6B_SG01040410_2002_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7A_MY47120078_2008_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7A_MY47120078_2008_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7A_MY47120078_2008_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7A_MY47120078_2008_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7A_MY47120078_2008_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7A_MY47120078_2008_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7B_MY47120086_2008_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7B_MY47120086_2008_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7B_MY47120086_2008_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7B_MY47120086_2008_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS7B_MY47120086_2008_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS7B_MY47120086_2008_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8A_MY47120229_2010_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8A_MY47120229_2010_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8A_MY47120229_2010_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8A_MY47120229_2010_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8A_MY47120229_2010_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8A_MY47120229_2010_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8B_MY47120230_2010_config() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8B_MY47120230_2010_config", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8B_MY47120230_2010_etc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8B_MY47120230_2010_etc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AS8B_MY47120230_2010_lic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AS8B_MY47120230_2010_lic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
